-- 코드를 입력하세요
# SELECT A. FLAVOR 
# FROM FIRST_HALF AS A
# JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER FROM JULY GROUP BY FLAVOR) AS B
# ON A.FLAVOR = B.FLAVOR
# WHERE RANK(3)
# ORDER BY (B.TOTAL_ORDER + A.TOTAL_ORDER) DESC
# LIMIT 3;

SELECT A.FLAVOR
FROM FIRST_HALF AS A
JOIN JULY AS B ON A.FLAVOR = B.FLAVOR
GROUP BY A.FLAVOR
ORDER BY SUM(A.TOTAL_ORDER) + SUM(B.TOTAL_ORDER) DESC 
LIMIT 3;